version: '3'

volumes:
  mongodb-data: {}

networks:
  random:

services:
  nginx:
    image: nginx:1.17-alpine
    container_name: "nginx"
    ports:
      - 80:80
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
  php-fpm:
    build: ./docker/php
    container_name: "php-fpm"
    volumes:
      - ./src:/var/www
    links:
      - db
    depends_on:
      - db
  db:
    build: ./docker/mysql
    container_name: "db"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql-files
      - ./mysql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: rameninfo
      MYSQL_USER: ramen_info
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      TZ: "Asia/Tokyo"
    command: --innodb-use-native-aio=0
  mongo:
    image: mongo
    container_name: "mongo"
    networks:
      - random
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret!
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb-data:/data/db'
  mongo-express:
    image: mongo-express:0.54.0
    networks:
      - random
    depends_on:
      - mongo
    container_name: "mongo-express"
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret!
  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
      - "8082:8080"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8083:8080"
    volumes:
      - ./swagger/openapi.json:/openapi.json
    environment:
      SWAGGER_JSON: /openapi.json
      # API_URL: ""
